---
title: "Data analysis"
date: "28/01/2022"
---

```{r setup, warning = F, message = F}
if (!require("dplyr")) install.packages("dplyr")
if (!require("tidyr")) install.packages("tidyr")
if (!require("survival")) install.packages("survival")
if (!require("stargazer")) install.packages("stargazer")

library(dplyr)
library(tidyr)
library(survival)
library(stargazer)
library(modeest)

setwd("/home/jan/Documents/thesis/2_data")

rm(list = ls())

load("data_output/data_4_class.RData")

#https://data.princeton.edu/wws509/r/recidivism
```

```{r}
data_covariates <- data_covariates %>% 
  filter(age >= 50) %>%
  filter(age <= age_retired) %>%
  group_by(mergeid) %>%
  mutate(retired = ifelse(!is.na(age_retired), 1, 0))

data_covariates$class_oesch8 <- relevel(as.factor(data_covariates$class_oesch8), ref = 'Production workers')
data_covariates$family_status <- relevel(as.factor(data_covariates$family_status), ref = 'married')
data_covariates$gender <- relevel(as.factor(data_covariates$gender), ref = 'Male')

# also include those not retiring
```

```{r}
breaks <- c(55, 59, 60, 61, 64, 65)

test <- survSplit(Surv(age, retired) ~ ., data = data_covariates, cut = breaks, episode = "interval", start = "start")

test$start <- ifelse(test$start == 0, 49, test$start)

test <- mutate(test, exposure = age - start, interval = factor(interval,  labels = paste("[", c(50, breaks), ",", c(breaks,100), "]", sep = "")))

test <- test %>% dplyr::select(mergeid, retired, interval, class_oesch8, gender, ill_health, start, age, age_retired, year, country, exposure, family_status, nchildren, education_years, job_tenure) %>% na.omit()

test <- test %>%
  mutate(retired = ifelse(age == age_retired, 1, 0)) %>%
  group_by(mergeid, age) %>%
  filter(year == min(year)) %>%
  group_by(mergeid, interval) %>%
  filter(age == max(age))

model_1 <- glm(retired ~ interval + class_oesch8 + gender + age + year + country + offset(log(exposure)), data = test, family = poisson(link = "log"))

stargazer(model_1, type = "text", omit = c("country", "exposure", "interval", "year", "Constant"), apply.coef=exp, t.auto = F, p.auto = F)
```

```{r}
model_1 <- glm(retired ~ interval + class_oesch8 + gender + age + year + country + offset(log(exposure)), data = test, family = poisson(link = "log"))

model_2 <- glm(retired ~ interval + class_oesch8 + gender + ill_health + age + year + country + offset(log(exposure)) + family_status + nchildren + education_years + job_tenure, data = test, family = poisson(link = "log"))

model_3 <- glm(retired ~ interval + class_oesch8*gender + age + year + country + offset(log(exposure)), data = test, family = poisson(link = "log"))

model_4 <- glm(retired ~ interval + class_oesch8*gender + ill_health + age + year + country + offset(log(exposure)) + family_status + nchildren + education_years + job_tenure, data = test, family = poisson(link = "log"))

stargazer(model_1, model_2, model_3, model_4, type = "text", omit = c("country", "exposure", "interval", "year", "Constant"), apply.coef=exp, t.auto = F, p.auto = F)
```