```{r setup, warning = F, message = F}
if (!require("dplyr")) install.packages("dplyr")
if (!require("tidyr")) install.packages("tidyr")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("TraMineR")) install.packages("TraMineR")
if (!require("TraMineRextras")) install.packages("TraMineRextras")
if (!require("WeightedCluster")) install.packages("WeightedCluster")

library(dplyr)
library(tidyr)
library(ggplot2)
library(TraMineR)
library(TraMineRextras)
library(WeightedCluster)

setwd("/home/jan/Documents/thesis/2_data")

rm(list = ls())

load("data_output/data_4_class.RData")
```

```{r}
#data_final <- data_covariates %>% filter(age >= 40 & country %in% c("Germany"))

data_final <- data_covariates %>% filter(age >= 40)

rm(data_covariates)
```

```{r}
work_history <- data_final %>%
  group_by(mergeid) %>%
  mutate(ind = ifelse(work_state == "RET" & lag(work_state) == "RET", 1, 0)) %>%
  filter(ind != 1) %>%
  slice(tail(row_number(), 7)) %>%
  mutate(distance = c(1:n()),
         age_enter = age_retired - 6) %>%
  select(-ind)

work_history <- work_history %>% select(mergeid, distance, work_state) %>%
  pivot_wider(names_from = distance, values_from = work_state) %>%
  filter(`7` == "RET")

colnames(work_history) <- c("mergeid", -6, -5, -4, -3, -2, -1, "retired")
```

```{r}
seq_history <- seqdef(work_history, 2:8, 
                   states = c("DIS", "DOM", "EDU", "FTE", "OLF", "PRE", "PTE", "RET", "UNE"), 
                   labels = c("DIS", "DOM", "EDU", "FTE", "OLF", "PRE", "PTE", "RET", "UNE"), 
                   with.missing = F)
```

```{r}
seq_distances <- seqdist(seq_history, method = "LCS", with.missing = T)

#seq_cluster <- kmeans(seq_distances, 5)
#seq_cluster <- pam(seq_distances, 5)

seq_cluster <- wcKMedRange(seq_distances, 2:10,  method = "PAMonce")

plot(seq_cluster, stat = c("ASW", "HC"), norm = "zscoremed", lwd = 1)

#seqdplot(seq_history, group = seq_cluster$clustering$cluster6, border = NA)
```

```{r}
work_history <- work_history %>% select(mergeid) %>% mutate(retired = 1)

work_history$cluster <- seq_cluster$clustering$cluster5

work_history <- work_history %>%
  mutate(
    cluster = case_when(
    cluster == 14714 ~ "Domestic exit",
    cluster == 14851 ~ "Transitional part-time retirement",
    cluster == 14868 ~ "Part-time employment exit",
    cluster == 14870 ~ "Full-time employment exit",
    cluster == 32 ~ "Part-time retirement",
    T ~ ""))

rm(seq_history, seq_distances, seq_cluster)

data_final <- data_final %>%
  mutate(retired = ifelse(age >= age_retired, 1, 0),
         retired = ifelse(is.na(retired), 0, retired)) %>%
  left_join(work_history, by = c("mergeid", "retired"))

data_final <- data_final %>%
  mutate(cluster = ifelse(is.na(cluster), "not_retired", cluster)) %>%
  select(-retired)

data_final <- data_final %>%
  group_by(mergeid) %>%
  mutate(ind = ifelse(work_state == "RET" & lag(work_state) == "RET", 1, 0)) %>%
  filter(ind != 1) %>%
  select(-ind)

rm(work_history)
```

```{r warning = F, message = F}
data_final <- data_final %>% select(mergeid, country, year_birth, gender, year, age, age_retired, year_retired, work_state, family_status, nchildren, ill_health, dist_retage, education_level, education_years, employed_years, job_tenure, class_isco_code, class_isco_label, class_code, class_oesch5, class_oesch8, class_oesch16, cluster, everything())
```

```{r}
save.image("data_output/data_final.RData")
```